const S={screen:"landing",person:0,pi:[[],[]],ri:0,ra:[],profile:null,result:null},K="lovematch_v3",$=x=>document.getElementById(x);
function save(){localStorage.setItem(K,JSON.stringify(S))}function esc(x){return String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");S.screen=id;save();scrollTo(0,0)}
function age(ds){let b=new Date(ds+"T00:00:00"),n=new Date(),a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()==b.getMonth()&&n.getDate()<b.getDate()))a--;return a}
function country(v){let x=COUNTRIES.find(c=>c[0]==v);return x?x[2]+" "+x[1]:"🌍 Other"}
function facts(pre){let ds=$(pre+"d").value;if(!ds){$(pre+"f").textContent="Enter a birthday.";return}let d=new Date(ds+"T00:00:00"),z=getZodiac(d),c=getChinese(d);$(pre+"f").innerHTML=`<b>${age(ds)} years old</b><br>${z[2]} ${z[1]} · ${c[2]} ${c[1]}`}
function setup(){["ac","bc"].forEach(id=>$(id).innerHTML='<option value="">Select country</option>'+COUNTRIES.map(c=>`<option value="${c[0]}">${c[2]} ${c[1]}</option>`).join(""));["ad","bd"].forEach(id=>$(id).oninput=()=>facts(id[0]))}
function profile(){let p={a:{name:$("an").value.trim(),country:$("ac").value,birthday:$("ad").value},b:{name:$("bn").value.trim(),country:$("bc").value,birthday:$("bd").value}};for(let k of["a","b"]){let d=new Date(p[k].birthday+"T00:00:00");p[k].age=age(p[k].birthday);p[k].z=getZodiac(d);p[k].c=getChinese(d)}p.diff=Math.abs(p.a.age-p.b.age);S.profile=p}
function tabs(){ $("tabs").innerHTML=["A","B"].map((x,i)=>`<button class="tab ${i==S.person?"sel":""}" data-i="${i}">Person ${x} — ${esc(S.profile[i?"b":"a"].name)}</button>`).join("");document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{S.person=+b.dataset.i;tabs();personQ()})}
function personQ(){let i=S.person,n=S.pi[i].length;if(n>=PQ.length){if(S.pi[0].length>=PQ.length&&S.pi[1].length>=PQ.length){$("pq").innerHTML='<h3>Personality complete ✨</h3><p>Both people have finished all personality questions.</p><div class="next"><button class="primary" id="toRel">Continue to Compatibility →</button></div>';$("toRel").onclick=()=>{S.ri=0;show("relationship");relQ()};return}S.person=S.pi[0].length<PQ.length?0:1;tabs();return} $("pp").textContent=`${n+1} / ${PQ.length}`;let old=S.pi[i][n];$("pq").innerHTML=`<h3>${PQ[n]}</h3><div class="ans">${PA[n].map((x,j)=>`<button class="${old==j?"sel":""}" data-j="${j}">${x}</button>`).join("")}</div><p class="micro">Person ${i?"B":"A"} answers independently.</p>`;document.querySelectorAll("#pq .ans button").forEach(b=>b.onclick=()=>{S.pi[i][n]=+b.dataset.j;save();personQ()})}
function relQ(){let i=S.ri,q=RQ[i],x=S.ra[i]||{};$("rp").textContent=`Question ${i+1} of ${RQ.length}`;$("rr").textContent=Math.round(i/RQ.length*100)+"%";$("rq").innerHTML=`<h3>${q[1]}</h3><div><b>PERSON A — ${esc(S.profile.a.name)}</b><div class="ans">${q.slice(2).map((v,j)=>`<button data-p="a" data-j="${j}" class="${x.a==j?"sel":""}">${v}</button>`).join("")}</div><br><b>PERSON B — ${esc(S.profile.b.name)}</b><div class="ans">${q.slice(2).map((v,j)=>`<button data-p="b" data-j="${j}" class="${x.b==j?"sel":""}">${v}</button>`).join("")}</div></div><div class="next"><button class="primary" id="rn">${i==RQ.length-1?"Calculate LoveMatch ✨":"Next →"}</button></div>`;document.querySelectorAll("#rq .ans button").forEach(b=>b.onclick=()=>{S.ra[i]=S.ra[i]||{};S.ra[i][b.dataset.p]=+b.dataset.j;relQ()});$("rn").onclick=()=>{x=S.ra[i];if(!x||x.a==null||x.b==null){toast("Both people must answer this question.");return}if(i<RQ.length-1){S.ri++;save();relQ()}else calculate()}}
function sim(a,b){let d=Math.abs(a-b);return d==0?100:d==1?82:d==2?64:48}
function scores(){let g={Communication:[],Affection:[],Lifestyle:[],Money:[],"Future Goals":[],Conflict:[],Trust:[],Fun:[]};S.ra.forEach((x,i)=>g[RQ[i][0]].push(sim(x.a,x.b)));let av=a=>Math.round(a.reduce((x,y)=>x+y,0)/a.length),o={};for(let k in g)o[k]=av(g[k]);o["Emotional Connection"]=Math.round(o.Affection*.4+o.Communication*.35+o.Conflict*.25);let ks=["Communication","Emotional Connection","Lifestyle","Future Goals","Trust","Fun","Affection","Money"];o["Fun & Interests"]=o.Fun;o.Overall=Math.round(ks.reduce((s,k)=>s+o[k],0)/ks.length);return o}
function pair(a,b){return a==b?78:((a+b)%3==0?84:70)}
function personality(i){let sc=[0,0,0,0,0];S.pi[i].forEach((v,q)=>sc[v]+=q%3+1);let m=Math.max(...sc),j=sc.indexOf(m);return PERSONALITIES[j]}
function calculate(){show("calc");let msgs=["Analyzing your answers...","Comparing your profiles...","Calculating your LoveMatch..."],i=0,t=setInterval(()=>{if(++i<msgs.length)$("ct").textContent=msgs[i];else{clearInterval(t);let z=pair(S.profile.a.z[0],S.profile.b.z[0]),c=pair(S.profile.a.c[0],S.profile.b.c[0]),pa=personality(0),pb=personality(1),pc=pair(pa[0],pb[0]),cat=scores();cat.Overall=Math.round(cat.Overall*.82+(z+c+pc)/3*.18);S.result={cat,z,c,pc,pa,pb};S.screen="donation";save();showDonation()}},650)}
function showDonation(){show("donation");$("donationPanel").hidden=true;window.scrollTo(0,0)}
function openResult(){show("results");render();save()}
function render(){let r=S.result,p=S.profile;$("names").textContent=p.a.name+" ❤️ "+p.b.name;$("score").textContent=r.cat.Overall+"%";$("score").style.setProperty("--p",r.cat.Overall+"%");$("headline").textContent=r.cat.Overall>=85?"Strong compatibility — you have several areas of alignment to explore together.":r.cat.Overall>=70?"Good alignment — you share several promising areas while leaving room to learn about each other.":"A mixed profile — there are clear points of connection and useful areas to explore together."; $("summary").innerHTML=[p.a,p.b].map(x=>`<article><h3>${esc(x.name)}</h3><p>${country(x.country)}</p><p>${x.age} years old · ${x.z[2]} ${x.z[1]} · ${x.c[2]} ${x.c[1]}</p></article>`).join("");let ks=["Communication","Emotional Connection","Lifestyle","Future Goals","Trust","Fun & Interests","Affection","Money"];$("scores").innerHTML=ks.map(k=>`<article><b>${k}</b><strong style="float:right">${r.cat[k]}%</strong><div class="bar"><i style="width:${r.cat[k]}%"></i></div></article>`).join("");let rank=ks.map(k=>[k,r.cat[k]]).sort((a,b)=>b[1]-a[1]);$("strengths").innerHTML=rank.slice(0,4).map(x=>`<p>💪 <b>${x[0]}</b> — ${x[1]}%</p>`).join("");$("friction").innerHTML=rank.slice(-3).map(x=>`<p>🌱 <b>${x[0]}</b> — ${x[1]}%, an area to explore together.</p>`).join("");$("recs").innerHTML=rank.slice(-3).map(x=>`<p>💡 ${rec(x[0],x[1])}</p>`).join("");$("zpanel").innerHTML=`<h3>♈ Entertainment-based zodiac interpretation</h3><p>${p.a.z[2]} ${p.a.z[1]} + ${p.b.z[2]} ${p.b.z[1]} · Zodiac Connection: ${r.z}%</p>`;$("cpanel").innerHTML=`<h3>🐉 Entertainment-based Chinese zodiac interpretation</h3><p>${p.a.c[2]} ${p.a.c[1]} + ${p.b.c[2]} ${p.b.c[1]} · Connection: ${r.c}%</p>`;$("ppanel").innerHTML=`<h3>✨ Fun Internet-Culture Personality Archetypes</h3><p>${r.pa[2]} ${r.pa[1]} + ${r.pb[2]} ${r.pb[1]} · Fun connection: ${r.pc}%</p><p class="micro">${r.pa[3]} ${r.pb[3]} These are not scientifically validated psychological types.</p>`}
function rec(k,s){let m={Communication:"Try setting aside uninterrupted time for honest conversations.",Lifestyle:"Compare your ideal week and choose activities that give both people energy.","Future Goals":"Talk openly about long-term expectations and priorities.",Trust:"Discuss what reliability, honesty and privacy look like for each of you.",Affection:"Ask what makes affection feel natural and appreciated.",Money:"Discuss spending, saving and bigger decisions before they become stressful.","Fun & Interests":"Alternate who chooses a date or activity.", "Emotional Connection":"Make room for gentle check-ins about feelings."};return s>=80?"Keep nurturing your strong "+k.toLowerCase()+" alignment.":m[k]}
function text(){let r=S.result,p=S.profile;return `❤️ Our LoveMatch\n${p.a.name} + ${p.b.name}\nCompatibility: ${r.cat.Overall}%\nCommunication: ${r.cat.Communication}%\nLifestyle: ${r.cat.Lifestyle}%\n#LoveMatch\n\nFun entertainment & self-reflection only — not scientifically validated.`}
function dl(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text()],{type:"text/plain"}));a.download="lovematch-result.txt";a.click()}
function toast(x){$("toast").textContent=x;$("toast").className="show";setTimeout(()=>$("toast").className="",1800)}
$("donateYes").onclick=()=>{
  $("donationPanel").hidden=false;
  $("donateYes").disabled=true;
  $("donateYes").textContent="Support details opened ✓";
  toast("Thank you! You can scan the QR or use the GCash number.");
  setTimeout(()=>$("donationPanel").scrollIntoView({behavior:"smooth",block:"center"}),50);
};
$("donateSkip").onclick=()=>openResult();
$("continueResult").onclick=()=>openResult();
$("copyGcash").onclick=async()=>{
  const n=$("gcashNumber").textContent.trim();
  try{
    await navigator.clipboard.writeText(n);
    $("copyGcash").textContent="Copied ✓";
    toast("GCash number copied.");
    setTimeout(()=>$("copyGcash").textContent="Copy",1600);
  }catch(e){
    toast("GCash number: "+n);
  }
};
$("start").onclick=()=>show("profiles");$("home").onclick=()=>show("landing");$("clear").onclick=()=>{localStorage.removeItem(K);location.reload()};setup();
$("form").onsubmit=e=>{e.preventDefault();profile();S.pi=[[],[]];S.ra=[];S.person=0;show("personality");tabs();personQ()};
$("share").onclick=async()=>{let t=text();if(navigator.share){try{await navigator.share({title:"Our LoveMatch",text:t});return}catch(e){}}try{await navigator.clipboard.writeText(t);toast("Result copied to clipboard.")}catch(e){dl()}};
$("save").onclick=()=>{dl();toast("Result saved.")};$("print").onclick=()=>print();$("new").onclick=()=>{localStorage.removeItem(K);location.reload()};
try{let old=JSON.parse(localStorage.getItem(K));if(old&&old.profile){Object.assign(S,old);for(let k of["a","b"]){let p=S.profile[k],d=new Date(p.birthday+"T00:00:00");p.age=age(p.birthday);p.z=getZodiac(d);p.c=getChinese(d)}show(S.screen);if(S.screen=="personality"){tabs();personQ()}if(S.screen=="relationship")relQ();if(S.screen=="donation")showDonation();if(S.screen=="results")render()}}catch(e){}